title: Debangan Mishra
description: Short tagline or your interests
theme: jekyll-theme-minimal

# Social links
google_scholar: https://scholar.google.com/citations?user=PnRWab4AAAAJ&hl=en
linkedin: https://www.linkedin.com/in/debangan-mishra-1a1a34209/
twitter: https://x.com/DebanganM10375
semantic_scholar: https://www.semanticscholar.org/author/Debangan-Mishra/2317979921

# Optional
show_downloads: false  # hide repo download link
