title: Your Name
description: Short tagline or your interests
theme: jekyll-theme-minimal

# Social links
google_scholar: https://scholar.google.com/citations?user=PnRWab4AAAAJ&hl=en
linkedin: https://www.linkedin.com/in/yourprofile
twitter: https://twitter.com/yourprofile
semantic_scholar: https://www.semanticscholar.org/author/Your-Name/ID

# Optional
show_downloads: false  # hide repo download link
